# ncbi-extract-acc.pbs
#PBS -N ncbi-extract-acc.pbs
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=12:00:00
#PBS -q microcluster
#PBS -j oe
cd $PBS_O_WORKDIR

### INPUT: list of SRA accessions
# DRR, ERR, and SRR prefixes means submitted to different databases: SRR to NCBI, ERR to EBI and DRR to DDBJ

### OUTPUT: tab-separated file with SRA accession, corresponding BioSample accession, and corresponding BioProject accession
# BioSample database stores metadata about each sample
# BioProject database stores information about research projects and links to data

input="ACC-LIST.txt"
output="sra-sample-proj.tsv"
bash ncbi-extract-acc.sh -i "$input" -o "$output" |& tee "warning.txt"
