# query-counts.pbs
#PBS -N query-counts
#PBS -l nodes=1:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=72:00:00
#PBS -q microcluster
#PBS -j oe
cd $PBS_O_WORKDIR

echo "count|RunAccession" > query-counts.txt

# Check counts for each query - for testing
for query in $(cat ACC-LIST.txt); do 
	counts=$(esearch -db "sra" -query "$query" | xtract -pattern "ENTREZ_DIRECT" -element "Count")
	echo "${counts}|${query}" >> query-counts.txt
done
